"""v2b domain model and additive persistence

Revision ID: 1ec5eceed8d4
Revises: 38cbecdcd585
Create Date: 2026-09-03 18:36:32.398264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ec5eceed8d4'
down_revision: Union[str, Sequence[str], None] = '38cbecdcd585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_connections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('google_account_email', sa.String(), nullable=True),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connected_by_actor', sa.String(), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_states',
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('pkce_verifier', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_table('contact_enrichments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prospect_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('call_group_id', sa.String(), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_digest', sa.String(), nullable=False),
    sa.Column('provider_person_id', sa.String(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('email_provider_status', sa.String(), nullable=True),
    sa.Column('email_provider_confidence', sa.Float(), nullable=True),
    sa.Column('email_is_catch_all', sa.Boolean(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('linkedin_asserted_full_name', sa.String(), nullable=True),
    sa.Column('linkedin_asserted_company_name', sa.String(), nullable=True),
    sa.Column('linkedin_asserted_company_domain', sa.String(), nullable=True),
    sa.Column('linkedin_asserted_title', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prospect_id', 'provider', 'call_group_id', name='uq_contact_enrichments_prospect_provider_group')
    )
    op.create_index(op.f('ix_contact_enrichments_prospect_id'), 'contact_enrichments', ['prospect_id'], unique=False)
    op.create_table('enrichment_calls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('call_group_id', sa.String(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('attempt_kind', sa.String(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('prospect_id', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('provider_request_id', sa.String(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('credits_used', sa.Float(), nullable=True),
    sa.Column('input_digest', sa.String(), nullable=True),
    sa.Column('output_digest', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_group_id', 'attempt', name='uq_enrichment_calls_group_attempt')
    )
    op.create_index(op.f('ix_enrichment_calls_run_id'), 'enrichment_calls', ['run_id'], unique=False)
    op.create_table('action_proposals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prospect_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('draft_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('sender_identifier', sa.String(), nullable=True),
    sa.Column('recipient_identifier', sa.String(), nullable=True),
    sa.Column('recipient_identity_key', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('hash_version', sa.String(), nullable=False),
    sa.Column('policy_version', sa.String(), nullable=False),
    sa.Column('policy_verdict', sa.String(), nullable=False),
    sa.Column('blocked_reasons', sa.JSON(), nullable=False),
    sa.Column('policy_snapshot', sa.JSON(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['outreach_drafts.id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['action_proposals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_id', 'content_hash', name='uq_action_proposals_draft_hash')
    )
    op.create_index(op.f('ix_action_proposals_prospect_id'), 'action_proposals', ['prospect_id'], unique=False)
    op.create_index(op.f('ix_action_proposals_run_id'), 'action_proposals', ['run_id'], unique=False)
    op.create_table('contact_channels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prospect_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('discovery_state', sa.String(), nullable=True),
    sa.Column('verification_state', sa.String(), nullable=True),
    sa.Column('identity_match_state', sa.String(), nullable=True),
    sa.Column('derivation_version', sa.String(), nullable=True),
    sa.Column('derived_from_enrichment_id', sa.String(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_status', sa.String(), nullable=True),
    sa.Column('last_attempt_error_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['derived_from_enrichment_id'], ['contact_enrichments.id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prospect_id', 'channel', name='uq_contact_channels_prospect_channel')
    )
    op.create_index(op.f('ix_contact_channels_prospect_id'), 'contact_channels', ['prospect_id'], unique=False)
    op.create_table('action_executions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('action_proposal_id', sa.String(), nullable=False),
    sa.Column('approval_id', sa.String(), nullable=True),
    sa.Column('prospect_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('recipient_identity_key', sa.String(), nullable=True),
    sa.Column('sender_identifier', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('message_id_header', sa.String(), nullable=True),
    sa.Column('provider_message_id', sa.String(), nullable=True),
    sa.Column('provider_thread_id', sa.String(), nullable=True),
    sa.Column('executor_id', sa.String(), nullable=True),
    sa.Column('dispatched', sa.Boolean(), nullable=False),
    sa.Column('outcome_class', sa.String(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('reconcile_attempts', sa.Integer(), nullable=False),
    sa.Column('messages_scanned', sa.Integer(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_type', sa.String(), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['action_proposal_id'], ['action_proposals.id'], ),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_action_executions_action_proposal_id'), 'action_executions', ['action_proposal_id'], unique=False)
    op.create_index(op.f('ix_action_executions_prospect_id'), 'action_executions', ['prospect_id'], unique=False)
    op.create_index(op.f('ix_action_executions_run_id'), 'action_executions', ['run_id'], unique=False)
    op.create_index('ix_action_executions_status_claimed_at', 'action_executions', ['status', 'claimed_at'], unique=False)
    op.create_index('uq_action_executions_live_recipient', 'action_executions', ['action_type', 'recipient_identity_key'], unique=True, sqlite_where=sa.text("origin = 'LIVE_EXTERNAL' AND action_type = 'EMAIL_SEND' AND status IN ('CLAIMED', 'IN_FLIGHT', 'SUCCEEDED', 'UNCERTAIN', 'ABANDONED')"), postgresql_where=sa.text("origin = 'LIVE_EXTERNAL' AND action_type = 'EMAIL_SEND' AND status IN ('CLAIMED', 'IN_FLIGHT', 'SUCCEEDED', 'UNCERTAIN', 'ABANDONED')"))
    op.create_table('action_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('action_execution_id', sa.String(), nullable=True),
    sa.Column('action_proposal_id', sa.String(), nullable=True),
    sa.Column('prospect_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_execution_id'], ['action_executions.id'], ),
    sa.ForeignKeyConstraint(['action_proposal_id'], ['action_proposals.id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_action_events_prospect_id_ts', 'action_events', ['prospect_id', 'ts'], unique=False)
    op.create_table('action_send_calls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('action_execution_id', sa.String(), nullable=False),
    sa.Column('call_group_id', sa.String(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('attempt_kind', sa.String(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('provider_request_id', sa.String(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('credits_used', sa.Float(), nullable=True),
    sa.Column('input_digest', sa.String(), nullable=True),
    sa.Column('output_digest', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['action_execution_id'], ['action_executions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_group_id', 'attempt', name='uq_action_send_calls_group_attempt')
    )
    op.create_index(op.f('ix_action_send_calls_action_execution_id'), 'action_send_calls', ['action_execution_id'], unique=False)
    # `batch_alter_table` rather than plain `op.add_column`/`op.alter_column`/
    # `op.create_foreign_key` — SQLite has no `ALTER TABLE ADD CONSTRAINT`/
    # `ALTER COLUMN`, so a plain sequence of those ops (what autogenerate
    # produces by default) works on Postgres but raises `NotImplementedError`
    # on SQLite. Batch mode uses the copy-and-move strategy on SQLite and
    # plain ALTER statements on every other dialect (Postgres included), so
    # one migration body is correct on both — required here because
    # `test_migration_drift.py` runs this same `upgrade head` unconditionally
    # against SQLite, not only against Postgres.
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scope', sa.String(), server_default='PROSPECT', nullable=False))
        batch_op.add_column(sa.Column('action_proposal_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('content_hash', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('hash_version', sa.String(), nullable=True))
        batch_op.create_foreign_key(
            'fk_approvals_action_proposal_id_action_proposals',
            'action_proposals',
            ['action_proposal_id'],
            ['id'],
        )
        batch_op.create_check_constraint(
            'ck_approvals_action_scope_complete',
            "scope <> 'ACTION' OR (action_proposal_id IS NOT NULL AND content_hash IS NOT NULL "
            "AND hash_version IS NOT NULL)",
        )

    with op.batch_alter_table('outreach_drafts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_hash', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('hash_version', sa.String(), server_default='v1', nullable=False))
        batch_op.alter_column('subject', existing_type=sa.VARCHAR(), nullable=True)
        batch_op.create_index('ix_outreach_drafts_prospect_id_channel', ['prospect_id', 'channel'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outreach_drafts', schema=None) as batch_op:
        batch_op.drop_index('ix_outreach_drafts_prospect_id_channel')
        batch_op.alter_column('subject', existing_type=sa.VARCHAR(), nullable=False)
        batch_op.drop_column('hash_version')
        batch_op.drop_column('content_hash')

    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_constraint('ck_approvals_action_scope_complete', type_='check')
        batch_op.drop_constraint('fk_approvals_action_proposal_id_action_proposals', type_='foreignkey')
        batch_op.drop_column('hash_version')
        batch_op.drop_column('content_hash')
        batch_op.drop_column('action_proposal_id')
        batch_op.drop_column('scope')

    op.drop_index(op.f('ix_action_send_calls_action_execution_id'), table_name='action_send_calls')
    op.drop_table('action_send_calls')
    op.drop_index('ix_action_events_prospect_id_ts', table_name='action_events')
    op.drop_table('action_events')
    op.drop_index('uq_action_executions_live_recipient', table_name='action_executions', sqlite_where=sa.text("origin = 'LIVE_EXTERNAL' AND action_type = 'EMAIL_SEND' AND status IN ('CLAIMED', 'IN_FLIGHT', 'SUCCEEDED', 'UNCERTAIN', 'ABANDONED')"), postgresql_where=sa.text("origin = 'LIVE_EXTERNAL' AND action_type = 'EMAIL_SEND' AND status IN ('CLAIMED', 'IN_FLIGHT', 'SUCCEEDED', 'UNCERTAIN', 'ABANDONED')"))
    op.drop_index('ix_action_executions_status_claimed_at', table_name='action_executions')
    op.drop_index(op.f('ix_action_executions_run_id'), table_name='action_executions')
    op.drop_index(op.f('ix_action_executions_prospect_id'), table_name='action_executions')
    op.drop_index(op.f('ix_action_executions_action_proposal_id'), table_name='action_executions')
    op.drop_table('action_executions')
    op.drop_index(op.f('ix_contact_channels_prospect_id'), table_name='contact_channels')
    op.drop_table('contact_channels')
    op.drop_index(op.f('ix_action_proposals_run_id'), table_name='action_proposals')
    op.drop_index(op.f('ix_action_proposals_prospect_id'), table_name='action_proposals')
    op.drop_table('action_proposals')
    op.drop_index(op.f('ix_enrichment_calls_run_id'), table_name='enrichment_calls')
    op.drop_table('enrichment_calls')
    op.drop_index(op.f('ix_contact_enrichments_prospect_id'), table_name='contact_enrichments')
    op.drop_table('contact_enrichments')
    op.drop_table('oauth_states')
    op.drop_table('gmail_connections')
    # ### end Alembic commands ###
