"""v2i_b live send allowance

V2-I-b Phase 5 — the rolling 24h Live send allowance. Two purely additive
tables: `live_send_allowance_lock` (exactly one seeded row, `id='default'`,
`version=0` — the guard row every reservation transaction UPDATEs first) and
`live_send_reservations` (one row per successfully reserved Live send,
`execution_id` unique/FK, never deleted/released). Nothing existing is
altered, renamed, or dropped.

Revision ID: 2384e7ddd94e
Revises: 94f688f37818
Create Date: 2026-09-08 09:21:39.485252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2384e7ddd94e'
down_revision: Union[str, Sequence[str], None] = '94f688f37818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


live_send_allowance_lock = sa.table(
    "live_send_allowance_lock",
    sa.column("id", sa.String()),
    sa.column("version", sa.Integer()),
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_send_allowance_lock',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_send_reservations',
    sa.Column('execution_id', sa.String(), nullable=False),
    sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['action_executions.id'], ),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_index(op.f('ix_live_send_reservations_reserved_at'), 'live_send_reservations', ['reserved_at'], unique=False)
    # ### end Alembic commands ###

    # Hand-added (not autogenerated): seed the exactly-one singleton row.
    # Every other schema-creation path (`db.py::create_all`,
    # `tests/conftest.py`) seeds it too — see
    # `repositories/live_send_allowance.py::ensure_singleton_seeded`.
    op.bulk_insert(live_send_allowance_lock, [{"id": "default", "version": 0}])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_live_send_reservations_reserved_at'), table_name='live_send_reservations')
    op.drop_table('live_send_reservations')
    op.drop_table('live_send_allowance_lock')
    # ### end Alembic commands ###
