"""initial schema

Revision ID: 38cbecdcd585
Revises: 
Create Date: 2026-09-02 06:05:01.632536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38cbecdcd585'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('canonical_domain', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_domain')
    )
    op.create_table('plays',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('objective_text', sa.Text(), nullable=False),
    sa.Column('icp_spec', sa.JSON(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('play_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('counters', sa.JSON(), nullable=False),
    sa.Column('provider_profile', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('last_event_seq', sa.Integer(), server_default='0', nullable=False),
    sa.Column('executor_id', sa.String(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['play_id'], ['plays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_runs_play_id_started_at', 'runs', ['play_id', 'started_at'], unique=False)
    op.create_index('ix_runs_status_heartbeat_at', 'runs', ['status', 'heartbeat_at'], unique=False)
    op.create_table('prospects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_stage', sa.String(), nullable=False),
    sa.Column('dedupe_key', sa.String(), nullable=False),
    sa.Column('duplicate_of', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['duplicate_of'], ['prospects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prospects_run_id'), 'prospects', ['run_id'], unique=False)
    op.create_table('run_events',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('prospect_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('run_id', 'seq')
    )
    op.create_table('agent_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('prospect_id', sa.String(), nullable=False),
    sa.Column('step_name', sa.String(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('input_digest', sa.String(), nullable=True),
    sa.Column('output_digest', sa.String(), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_tasks_prospect_step', 'agent_tasks', ['prospect_id', 'step_name'], unique=False)
    op.create_index('ix_agent_tasks_run_prospect', 'agent_tasks', ['run_id', 'prospect_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prospect_id', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prospect_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('persona', sa.Boolean(), nullable=False),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('verification', sa.String(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prospect_id', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('source_provider', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_prospect_id'), 'evidence', ['prospect_id'], unique=False)
    op.create_table('icp_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prospect_id', sa.String(), nullable=False),
    sa.Column('overall', sa.Integer(), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('modifiers', sa.JSON(), nullable=False),
    sa.Column('disqualified', sa.Boolean(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rubric_version', sa.String(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prospect_id')
    )
    op.create_table('llm_calls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('call_group_id', sa.String(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('attempt_kind', sa.String(), nullable=False),
    sa.Column('schema_round', sa.Integer(), nullable=False),
    sa.Column('transport_retry_index', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('play_id', sa.String(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('prospect_id', sa.String(), nullable=True),
    sa.Column('step_name', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('reasoning_effort', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('tokens_total', sa.Integer(), nullable=False),
    sa.Column('reasoning_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('provider_request_id', sa.String(), nullable=True),
    sa.Column('incomplete_reason', sa.String(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('input_digest', sa.String(), nullable=True),
    sa.Column('output_digest', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['play_id'], ['plays.id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_group_id', 'attempt', name='uq_llm_calls_group_attempt')
    )
    op.create_index(op.f('ix_llm_calls_run_id'), 'llm_calls', ['run_id'], unique=False)
    op.create_table('outreach_drafts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prospect_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('claim_map', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prospect_id', sa.String(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('checks', sa.JSON(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_calls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('call_group_id', sa.String(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('attempt_kind', sa.String(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('prospect_id', sa.String(), nullable=True),
    sa.Column('play_id', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('query_group_id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('rendered_query', sa.Text(), nullable=True),
    sa.Column('query_digest', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('selected_count', sa.Integer(), nullable=False),
    sa.Column('provider_request_id', sa.String(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('chars_retrieved', sa.Integer(), nullable=False),
    sa.Column('credits_used', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['play_id'], ['plays.id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_group_id', 'attempt', name='uq_search_calls_group_attempt')
    )
    op.create_index(op.f('ix_search_calls_run_id'), 'search_calls', ['run_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prospect_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('grounded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_prospect_id'), 'signals', ['prospect_id'], unique=False)
    op.create_table('source_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('search_call_id', sa.String(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('prospect_id', sa.String(), nullable=True),
    sa.Column('ref', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('canonical_url', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('full_text_length', sa.Integer(), nullable=True),
    sa.Column('content_sha256', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_result_id', sa.String(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('identity_key', sa.String(), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('canonical_source_id', sa.String(), nullable=True),
    sa.Column('evidence_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_source_id'], ['source_documents.id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['search_call_id'], ['search_calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_prospect_id'), 'source_documents', ['prospect_id'], unique=False)
    op.create_index(op.f('ix_source_documents_run_id'), 'source_documents', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_documents_run_id'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_prospect_id'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_signals_prospect_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_search_calls_run_id'), table_name='search_calls')
    op.drop_table('search_calls')
    op.drop_table('review_results')
    op.drop_table('outreach_drafts')
    op.drop_index(op.f('ix_llm_calls_run_id'), table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_table('icp_scores')
    op.drop_index(op.f('ix_evidence_prospect_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_table('contacts')
    op.drop_table('approvals')
    op.drop_index('ix_agent_tasks_run_prospect', table_name='agent_tasks')
    op.drop_index('ix_agent_tasks_prospect_step', table_name='agent_tasks')
    op.drop_table('agent_tasks')
    op.drop_table('run_events')
    op.drop_index(op.f('ix_prospects_run_id'), table_name='prospects')
    op.drop_table('prospects')
    op.drop_index('ix_runs_status_heartbeat_at', table_name='runs')
    op.drop_index('ix_runs_play_id_started_at', table_name='runs')
    op.drop_table('runs')
    op.drop_table('plays')
    op.drop_table('companies')
    # ### end Alembic commands ###
